// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGLoadingScreen.h"

void SFGLoadingScreen::Initialize(){ }
void SFGLoadingScreen::Shutdown(){ }
TSharedPtr< class ISlateStyle > SFGLoadingScreen::Get(){ return TSharedPtr<class ISlateStyle>(); }
FName SFGLoadingScreen::GetStyleSetName(){ return FName(); }
FString SFGLoadingScreen::InContent( const FString& relativePath, const ANSICHAR* extension){ return FString(); }
void SFGSpinnerLoader::SetPeriod( float inPeriod){ }
int32 SFGSpinnerLoader::OnPaint( const FPaintArgs& args, const FGeometry& allottedGeometry, const FSlateRect& myCullingRect, FSlateWindowElementList& outDrawElements, int32 layerId, const FWidgetStyle& inWidgetStyle, bool isParentEnabled) const{ return int32(); }
FVector2D SFGSpinnerLoader::ComputeDesiredSize(float) const{ return FVector2D(); }
void SFGSpinnerLoader::ConstructSequence(){ }
