// This file has been automatically generated by the Unreal Header Implementation tool

#include "Representation/FGWheeledVehicleRepresentation.h"

UFGWheeledVehicleRepresentation::UFGWheeledVehicleRepresentation() : Super() {
	this->mBackgroundIsPrimaryColor = false;
}
bool UFGWheeledVehicleRepresentation::GetShouldShowInCompass() const{ return bool(); }
bool UFGWheeledVehicleRepresentation::IsWarningIndicatorVisible(AActor* realActor, FLinearColor& out_warningIndicatorColor) const{ return bool(); }
void UFGWheeledVehicleRepresentation::UpdateActorRepresentation(){ }
