// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGTradingPostHologram.h"

void AFGTradingPostHologram::GetLifetimeReplicatedProps( TArray< FLifetimeProperty >& OutLifetimeProps) const{ }
void AFGTradingPostHologram::CheckValidPlacement(){ }
void AFGTradingPostHologram::SpawnChildren(  UFGBuildGunStateBuild* state){ }
AActor* AFGTradingPostHologram::Construct( TArray< AActor* >& out_children){ return nullptr; }
USceneComponent* AFGTradingPostHologram::SetupComponent( USceneComponent* attachParent, UActorComponent* componentTemplate, const FName& componentName){ return nullptr; }
void AFGTradingPostHologram::SetHologramLocationAndRotation( const FHitResult& hitResult){ }
