// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGReplicationDetailActor_Storage.h"

AFGReplicationDetailActor_Storage::AFGReplicationDetailActor_Storage(){ }
void AFGReplicationDetailActor_Storage::GetLifetimeReplicatedProps( TArray<FLifetimeProperty>& OutLifetimeProps) const{ }
void AFGReplicationDetailActor_Storage::InitReplicationDetailActor(  AFGBuildable* owningActor){ }
void AFGReplicationDetailActor_Storage::FlushReplicationActorStateToOwner(){ }
