// This file has been automatically generated by the Unreal Header Implementation tool

#include "OnlineFriend.h"

bool UOnlineFriend::IsPlayingThisGame() const{ return bool(); }
UCommonUserSubsystem* UOnlineFriend::GetSubsystem() const{ return nullptr; }
ULocalUserInfo* UOnlineFriend::GetLocalUserInfo() const{ return nullptr; }
UOnlineUserPresence* UOnlineFriend::GetPresence(UOnlineIntegrationBackend* Backend) const{ return nullptr; }
USessionInformation* UOnlineFriend::GetGameSession() const { return nullptr; }
EOnlineRelationship UOnlineFriend::GetRelationshipForBackend(UOnlineIntegrationBackend* Backend) const{ return EOnlineRelationship(); }
UOnlineUserInfo* UOnlineFriend::GetOnlineUser() const{ return nullptr; }
EOnlineUserPresenceStatus UOnlineFriend::GetPresenceStatus(UOnlineIntegrationBackend* Backend) const{ return EOnlineUserPresenceStatus(); }
EOnlineUserPresenceJoinability UOnlineFriend::GetPresenceJoinability(UOnlineIntegrationBackend* Backend) const{ return EOnlineUserPresenceJoinability(); }
EOnlineUserPresenceGameStatus UOnlineFriend::GetPresenceGameStatus(UOnlineIntegrationBackend* Backend) const{ return EOnlineUserPresenceGameStatus(); }
