// This file has been automatically generated by the Unreal Header Implementation tool

#include "OnlineAsyncOperation.h"

void UOnlineAsyncOperation::Cancel(){ }
FDelegateHandle UOnlineAsyncOperation::AddOperationFinishedDelegate(FOnOnlineAsyncOperationCompleted_Native::FDelegate &&Delegate){ return FDelegateHandle(); }
bool UOnlineAsyncOperation::HasErrors() const{ return bool(); }
void UOnlineAsyncOperation::NotifySequenceFinished(){ }
void UOnlineAsyncOperation::SetStatus(EOnlineAsyncOperationStatus OperationStatus){ }
void UOnlineAsyncOperation::UpdateStatus(EOnlineAsyncOperationStatus OperationStatus){ }
