// This file has been automatically generated by the Unreal Header Implementation tool

#include "SessionMemberInformation.h"

void USessionMemberInformation::SetPlayerState(APlayerState* InPlayerState){ }
void USessionMemberInformation::SetOnlineUserInfo(UOnlineUserInfo* InOnlineUserInfo){ }
void USessionMemberInformation::SetPlayingPlatformName(const FName& InPlayingPlatformName){ }
void USessionMemberInformation::SetPlatformAvatarURL(const FString& InPlatformAvatarURL){ }
void USessionMemberInformation::ShowProfileUI(){ }
