// This file has been automatically generated by the Unreal Header Implementation tool

#include "Creature/FGCreatureSeat.h"

void AFGCreatureSeat::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const {
	Super::GetLifetimeReplicatedProps(OutLifetimeProps);
	DOREPLIFETIME(AFGCreatureSeat, mMountedCreature);
}
void AFGCreatureSeat::BeginPlay(){ }
void AFGCreatureSeat::AttachDriver( AFGCharacterPlayer* driver){ }
