// This file has been automatically generated by the Unreal Header Implementation tool

#include "Creature/FGCreatureMovementComponent.h"

void UFGCreatureMovementComponent::BeginPlay(){ }
void UFGCreatureMovementComponent::OnCharacterStuckInGeometry(const FHitResult* Hit){ }
void UFGCreatureMovementComponent::OnMovementModeChanged(EMovementMode PreviousMovementMode, uint8 PreviousCustomMode){ }
bool UFGCreatureMovementComponent::ResolvePenetrationImpl(const FVector& Adjustment, const FHitResult& Hit, const FQuat& NewRotation){ return bool(); }
