// This file has been automatically generated by the Unreal Header Implementation tool

#include "User/OnlineUserPresence.h"

EOnlineUserPresenceStatus UOnlineUserPresence::GetStatus() const{ return EOnlineUserPresenceStatus(); }
EOnlineUserPresenceJoinability UOnlineUserPresence::GetJoinability() const{ return EOnlineUserPresenceJoinability(); }
EOnlineUserPresenceGameStatus UOnlineUserPresence::GetGameStatus() const{ return EOnlineUserPresenceGameStatus(); }
FString UOnlineUserPresence::GetStatusString() const{ return FString(); }
FString UOnlineUserPresence::GetRichPresenceString() const{ return FString(); }
const TMap<FString, FString>& UOnlineUserPresence::GetProperties() const{ return *(new TMap<FString, FString>); }
UOnlineIntegrationBackend* UOnlineUserPresence::GetBackend() const{ return nullptr; }
