// This file has been automatically generated by the Unreal Header Implementation tool

#include "User/OnlineUserPresencePrivate.h"

void UOnlineUserPresencePrivate::Init(UOnlineIntegrationBackend* backend){ }
void UOnlineUserPresencePrivate::Update(TSharedRef<const UE::Online::FUserPresence> OnlinePresence){ }
