// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGAggroTargetInterface.h"

UFGAggroTargetInterface::UFGAggroTargetInterface(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) {}
