// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGAttackMelee.h"

void UFGAttackMelee::PerformAttack(TScriptInterface< IFGAggroTargetInterface >	aggroTarget,  AFGEnemy* sourceActor){ }
