// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGAttackMeleeJump.h"

UFGAttackMeleeJump::UFGAttackMeleeJump(){ }
void UFGAttackMeleeJump::PerformAttack( TScriptInterface< IFGAggroTargetInterface >	aggroTarget,  AFGEnemy* sourceActor){ }
