// This file has been automatically generated by the Unreal Header Implementation tool

#include "DamageTypes/FGDamageType.h"

UFGDamageType::UFGDamageType(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) { }
