// This file has been automatically generated by the Unreal Header Implementation tool

#include "BlueprintObjectReaderFName.h"

FBlueprintObjectReaderFName::FBlueprintObjectReaderFName(UObject* Obj, UWorld* World, TArray<uint8>& InBytes, const FArchive& InnerArchive) : FObjectReader(Obj, InBytes), mWorld(World) { }
FBlueprintObjectReaderFName& FBlueprintObjectReaderFName::operator<<( UObject*& Res){ return *(this); }
FArchive& FBlueprintObjectReaderFName::operator<<( FName& N){ return *(new FArchive); }
FArchive& FBlueprintObjectReaderFName::operator<<(FObjectPtr& Res){ return *(new FArchive); }
