// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGAnimNotify_Landed.h"

UFGAnimNotify_Landed::UFGAnimNotify_Landed(){ }
FString UFGAnimNotify_Landed::GetNotifyName_Implementation() const{ return FString(); }
void UFGAnimNotify_Landed::Notify(USkeletalMeshComponent* meshComp, UAnimSequenceBase* animation){ }
