// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGBuildablePillar.h"
#include "Components/SceneComponent.h"
#include "FGColoredInstanceMeshProxy.h"

AFGBuildablePillar::AFGBuildablePillar() : Super() {
	this->mSize.X = 0.0;
	this->mSize.Y = 0.0;
	this->mSize.Z = 0.0;
}
