// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGCrashSiteDebris.h"
#include "Components/BoxComponent.h"
#include "Components/SceneComponent.h"

#if WITH_EDITOR
void AFGCrashSiteDebris::PreSave(FObjectPreSaveContext SaveContext){ }
void AFGCrashSiteDebris::PreEditChange(FProperty* PropertyAboutToChange){ }
void AFGCrashSiteDebris::PostEditChangeProperty(FPropertyChangedEvent& PropertyChangedEvent){ Super::PostEditChangeProperty(PropertyChangedEvent); }
void AFGCrashSiteDebris::Tick(float dt){ Super::Tick(dt); }
bool AFGCrashSiteDebris::ShouldTickIfViewportsOnly() const{ return bool(); }
void AFGCrashSiteDebris::ResetSavedSimulation(){ }
void AFGCrashSiteDebris::SpawnSimulation(){ }
void AFGCrashSiteDebris::SaveCurrentSimulation(){ }
void AFGCrashSiteDebris::DestroyCurrentSimulation(){ }
void AFGCrashSiteDebris::CacheDebrisSpawnLocations(){ }
#endif 
#if WITH_EDITOR
bool AFGCrashSiteDebris::IsLocationWithinSimulationDistance(const FVector& location) const{ return bool(); }
FTransform AFGCrashSiteDebris::OrientItemTransformUp(const FTransform& originalTransform, float boxExtent){ return FTransform(); }
void AFGCrashSiteDebris::TickCurrentSimulation(float dt){ }
void AFGCrashSiteDebris::DestroySavedSimulation(){ }
void AFGCrashSiteDebris::SpawnSavedSimulation(){ }
#endif 
#if WITH_EDITORONLY_DATA
#endif 
AFGCrashSiteDebris::AFGCrashSiteDebris() : Super() {
	this->mLinkedDropPod = nullptr;
	this->NetCullDistanceSquared = 2025000000.0;
	this->RootComponent = CreateDefaultSubobject<USceneComponent>(TEXT("Root"));
}
void AFGCrashSiteDebris::PreSaveGame_Implementation(int32 saveVersion, int32 gameVersion){ }
void AFGCrashSiteDebris::PostSaveGame_Implementation(int32 saveVersion, int32 gameVersion){ }
void AFGCrashSiteDebris::PreLoadGame_Implementation(int32 saveVersion, int32 gameVersion){ }
void AFGCrashSiteDebris::PostLoadGame_Implementation(int32 saveVersion, int32 gameVersion){ }
void AFGCrashSiteDebris::GatherDependencies_Implementation(TArray< UObject* >& out_dependentObjects){ }
bool AFGCrashSiteDebris::NeedTransform_Implementation(){ return bool(); }
bool AFGCrashSiteDebris::ShouldSave_Implementation() const{ return bool(); }
#if WITH_EDITOR
#endif 
#if WITH_EDITORONLY_DATA
#endif 
AFGCrashSiteDebrisItemBox::AFGCrashSiteDebrisItemBox() : Super() {
	this->mBoxComponent = CreateDefaultSubobject<UBoxComponent>(TEXT("ItemBox"));
	this->RootComponent = mBoxComponent;
}
#if WITH_EDITORONLY_DATA
#endif 
