// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGCreateOfflineSessionPrompt.h"

void UFGCreateOfflineSessionPrompt::SetDelegate(FOnlineSessionPromptResultKnown inDelegate){ }
void UFGCreateOfflineSessionPrompt::CancelSessionCreation(){ }
void UFGCreateOfflineSessionPrompt::CreateOfflineSession(){ }
