// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGFactorySettings.h"
#include "FGRecipeShortcut.h"
#include "Equipment/FGBuildGun.h"
#include "FGFactoryCustomizationShortcut.h"
#include "Equipment/FGResourceScanner.h"

UFGFactorySettings::UFGFactorySettings() : Super() {
	this->mDefaultValidPlacementMaterial = nullptr;
	this->mDefaultValidPlacementMaterialSimplified = nullptr;
	this->mDefaultInvalidPlacementMaterial = nullptr;
	this->mDefaultInputConnectionMaterial = nullptr;
	this->mDefaultOutputConnectionMaterial = nullptr;
	this->mDefaultNeutralConnectionMaterial = nullptr;
	this->mDefaultPowerConnectionMaterial = nullptr;
	this->mDefaultFactoryColor_Primary.R = 0.0;
	this->mDefaultFactoryColor_Primary.G = 0.0;
	this->mDefaultFactoryColor_Primary.B = 0.0;
	this->mDefaultFactoryColor_Primary.A = 0.0;
	this->mDefaultFactoryColor_Secondary.R = 0.0;
	this->mDefaultFactoryColor_Secondary.G = 0.0;
	this->mDefaultFactoryColor_Secondary.B = 0.0;
	this->mDefaultFactoryColor_Secondary.A = 0.0;
	this->mDefaultAttachmentPointConnectionMesh = nullptr;
	this->mDefaultConveyorConnectionFrameMesh = nullptr;
	this->mDefaultConveyorConnectionArrowMesh = nullptr;
	this->mDefaultPipeConnectionFrameMesh = nullptr;
	this->mDefaultPipeConnectionArrowMesh = nullptr;
	this->mDefaultPowerConnectionMesh = nullptr;
	this->mClearanceMesh = nullptr;
	this->mClearanceMaterial = nullptr;
	this->mHologramLoopSound = nullptr;
	this->mHologramSnapSound = nullptr;
	this->mBuildGuideMesh = nullptr;
	this->mBuildGuideWidth = 30.0;
	this->mBuildGuideMaterial = nullptr;
	this->mSignUprightIndicatorMesh = nullptr;
	this->mSignUprightIndicatorMaterial = nullptr;
	this->mInventoryDropCrate = nullptr;
	this->mPowerShardClass = nullptr;
	this->mBuildEffect = nullptr;
	this->mDismantleEffect = nullptr;
	this->mDismantlePendingMaterial = nullptr;
	this->mBuildGunClass = AFGBuildGun::StaticClass();
	this->mResourceScannerClass = AFGResourceScanner::StaticClass();
	this->mResourceMinerClass = nullptr;
	this->mLegMesh = nullptr;
	this->mFootMesh = nullptr;
	this->mMaxFeetLength = 1000.0;
	this->mRecipeShortcutClass = UFGRecipeShortcut::StaticClass();
	this->mCustomizationShortcutClass = UFGFactoryCustomizationShortcut::StaticClass();
	this->mNumHotbars = 2;
	this->mNumPresetHotbars = 2;
	this->mNumSlotsPerHotbar = 10;
	this->mFluidToInventoryStackRate = 0;
	this->mInventoryStackToFluidRate = 0;
	this->mAddedPipeProductionPressure = 0.0;
}
UAkAudioEvent* UFGFactorySettings::GetRandomConstructionSound(){ return nullptr; }
UAkAudioEvent* UFGFactorySettings::GetRandomDismantleSound(){ return nullptr; }
float UFGFactorySettings::GetPuddleRequirementForViscosity(float viscosity){ return float(); }
UFGFactorySettings* UFGFactorySettings::Get(){ return nullptr; }
