// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGFoliageResourceUserData.h"

void UFGFoliageResourceUserData::PostLoad(){ Super::PostLoad(); }
FText UFGFoliageResourceUserData::GetLookAtText() const{ return FText(); }
bool UFGFoliageResourceUserData::IdentifiesWith( TSubclassOf<  UFGFoliageIdentifier > identifier) const{ return bool(); }
bool UFGFoliageResourceUserData::MeshHasIdentifier( UStaticMesh* mesh, TSubclassOf<  UFGFoliageIdentifier > identifier){ return bool(); }
UParticleSystem* UFGFoliageResourceUserData::GetExplosionDestroyedEffect() const{ return nullptr; }
