// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGFrontendStateComponent.h"

UFGFrontendStateComponent::UFGFrontendStateComponent(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) {
	this->mAuthenticationSequence = nullptr;
	this->mOnlineIntegrationModeModel = nullptr;
}
void UFGFrontendStateComponent::BeginPlay(){ Super::BeginPlay(); }
void UFGFrontendStateComponent::EndPlay(const EEndPlayReason::Type endPlayReason){ Super::EndPlay(endPlayReason); }
void UFGFrontendStateComponent::BootstrapAuth(){  }
void UFGFrontendStateComponent::OnOnlineIntegrationModeChanged(EOnlineIntegrationMode mode, bool bInvokedByUser){  }
void UFGFrontendStateComponent::AuthenticationSequenceComplete(UOnlineAsyncOperation* InAsyncOp){ }
void UFGFrontendStateComponent::StartConsoleFlow(bool bSuppressErrors){  }
void UFGFrontendStateComponent::OnPremiumChecked(bool hasPremium){  }
void UFGFrontendStateComponent::TickCheckInvalidOnlineIntegrationState(bool suppressDisconectNotification){ }
void UFGFrontendStateComponent::OnlineModeSelectionConfirmed(bool popupConfirmed){ }
void UFGFrontendStateComponent::TryShowMainScreen(){ }
void UFGFrontendStateComponent::ShowUGCCommRestrictionDialog(){  }
void UFGFrontendStateComponent::HandleAppResume(){  }
void UFGFrontendStateComponent::HandleAppSuspend(){ }
void UFGFrontendStateComponent::HandleProtocolActivationReceived(){ }
bool UFGFrontendStateComponent::IsOnlineStateValidAndOnline(){ return false; }
void UFGFrontendStateComponent::RecalibrateAfterAppResume(){ }
