// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGGameSessionOnline.h"

AFGGameSessionOnline::AFGGameSessionOnline() : Super() {
	this->mSessionInformation = nullptr;
}
void AFGGameSessionOnline::UpdateGameSession(){ }
void AFGGameSessionOnline::Destroyed(){ Super::Destroyed(); }
void AFGGameSessionOnline::InitOptions(const FString& options){ }
void AFGGameSessionOnline::HandleMatchHasStarted(){ }
void AFGGameSessionOnline::HandleMatchHasEnded(){ }
void AFGGameSessionOnline::PostLogin(APlayerController* newPlayer){ }
void AFGGameSessionOnline::RegisterPlayer(APlayerController* NewPlayer, const FUniqueNetIdRepl& UniqueId, bool bWasFromInvite){ }
void AFGGameSessionOnline::UnregisterPlayer(const APlayerController* ExitingPlayer){ }
void AFGGameSessionOnline::UnregisterPlayer(FName InSessionName, const FUniqueNetIdRepl& UniqueId){ }
void AFGGameSessionOnline::ListenForIntroSequenceUpdated(){ }
void AFGGameSessionOnline::IntroSequenceUpdated(){ }
