// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGInteractableMarker.h"
#include "Components/SceneComponent.h"
#include "Components/SplineMeshComponent.h"
#include "Components/WidgetComponent.h"

AFGInteractableMarker::AFGInteractableMarker() : Super() {
	this->mIconWidget = CreateDefaultSubobject<UWidgetComponent>(TEXT("Icon"));
	this->mSplineMesh = CreateDefaultSubobject<USplineMeshComponent>(TEXT("SplineMesh"));
	this->mDesiredScreenRadius = 10.0;
	this->mTrackedActor = nullptr;
	this->mCachePlayerController = nullptr;
	this->PrimaryActorTick.TickGroup = ETickingGroup::TG_PrePhysics;
	this->PrimaryActorTick.EndTickGroup = ETickingGroup::TG_PrePhysics;
	this->PrimaryActorTick.bTickEvenWhenPaused = false;
	this->PrimaryActorTick.bCanEverTick = true;
	this->PrimaryActorTick.bStartWithTickEnabled = true;
	this->PrimaryActorTick.bAllowTickOnDedicatedServer = true;
	this->PrimaryActorTick.TickInterval = 0.0;
	this->RootComponent = CreateDefaultSubobject<USceneComponent>(TEXT("RootComponent"));
	this->mIconWidget->SetupAttachment(RootComponent);
	this->mSplineMesh->SetupAttachment(RootComponent);
}
void AFGInteractableMarker::Tick(float dt){ }
void AFGInteractableMarker::SetTrackedActor( AActor* trackedActor){ }
void AFGInteractableMarker::BeginPlay(){ }
