// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGMapManager.h"
#include "Net/UnrealNetwork.h"

DEFINE_LOG_CATEGORY(LogMapManager);

AFGMapManager* AFGMapManager::Get(UWorld* world){ return nullptr; }
AFGMapManager* AFGMapManager::Get(UObject* worldContext){ return nullptr; }
AFGMapManager::AFGMapManager() : Super() {
	this->mFogOfWarTexture = nullptr;
	this->mCachedMinimapCaptureActor = nullptr;
	this->mActorRepresentationManager = nullptr;
	this->PrimaryActorTick.TickGroup = ETickingGroup::TG_DuringPhysics;
	this->PrimaryActorTick.EndTickGroup = ETickingGroup::TG_PrePhysics;
	this->PrimaryActorTick.bTickEvenWhenPaused = false;
	this->PrimaryActorTick.bCanEverTick = true;
	this->PrimaryActorTick.bStartWithTickEnabled = true;
	this->PrimaryActorTick.bAllowTickOnDedicatedServer = true;
	this->PrimaryActorTick.TickInterval = 0.1;
	this->SetHidden(false);
}
void AFGMapManager::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const {
	Super::GetLifetimeReplicatedProps(OutLifetimeProps);
	DOREPLIFETIME(AFGMapManager, mMapMarkers);
}
void AFGMapManager::BeginPlay(){ Super::BeginPlay(); }
void AFGMapManager::EndPlay(const EEndPlayReason::Type endPlayReason){ Super::EndPlay(endPlayReason); }
void AFGMapManager::Tick(float dt){ Super::Tick(dt); }
void AFGMapManager::DisplayDebug( UCanvas* canvas, const  FDebugDisplayInfo& debugDisplay, float& YL, float& YPos){ }
void AFGMapManager::PreSaveGame_Implementation(int32 saveVersion, int32 gameVersion){ }
void AFGMapManager::PostSaveGame_Implementation(int32 saveVersion, int32 gameVersion){ }
void AFGMapManager::PreLoadGame_Implementation(int32 saveVersion, int32 gameVersion){ }
void AFGMapManager::PostLoadGame_Implementation(int32 saveVersion, int32 gameVersion){ }
void AFGMapManager::GatherDependencies_Implementation(TArray< UObject* >& out_dependentObjects){ }
bool AFGMapManager::NeedTransform_Implementation(){ return bool(); }
bool AFGMapManager::ShouldSave_Implementation() const{ return bool(); }
bool AFGMapManager::AddNewMapMarker(const FMapMarker& mapMarker, FMapMarker& out_NewMapMarker){ return bool(); }
void AFGMapManager::UpdateMapMarker(const FMapMarker& mapMarker, bool localUpdateOnly){ }
void AFGMapManager::GetMapMarkers(TArray<FMapMarker>& out_mapMarkers){ }
bool AFGMapManager::CanAddNewMapMarker() const{ return bool(); }
void AFGMapManager::RemoveMapMarker(const FMapMarker& mapMarker){ }
void AFGMapManager::SetMapMarkerComponentsVisible(bool visible){ }
void AFGMapManager::Authority_UpdateMapMarker(const FMapMarker& mapMarker){  }
void AFGMapManager::Authority_RemoveMapMarkerByID(const FGuid& markerGuid){  }
void AFGMapManager::SpawnMapMarkerObjectOfType(const FMapMarker& mapMarker){ }
void AFGMapManager::RemoveMapMarkerObjectOfType(const FMapMarker& mapMarker){ }
void AFGMapManager::CreateOrUpdateMarkerRepresentation(const FMapMarker& mapMarker){  }
void AFGMapManager::UpdateMarkerComponentVisibility(){  }
bool AFGMapManager::FindMapMarkerFromHitResult(const FHitResult& hitResult, FMapMarker& out_mapMarker){ return bool(); }
UFGMapMarkerRepresentation* AFGMapManager::FindMapMarkerRepresentation(const FMapMarker& mapMarker){ return nullptr; }
UFGMapMarkerRepresentation* AFGMapManager::FindMapMarkerRepresentation(const FGuid mapMarkerGUID){ return nullptr; }
FLinearColor AFGMapManager::IsMarkerHighlighted(const FMapMarker& mapMarker,  bool& out_IsHighlighted,  bool& out_HighlightedByLocalPlayer){ return FLinearColor(); }
void AFGMapManager::SetMarkerHighlighted(const FMapMarker& mapMarker, bool highlighted){ }
void AFGMapManager::SetHighLightMarker( AFGPlayerState* fgPlayerState, UFGActorRepresentation* actorRepresentation){ }
void AFGMapManager::OnMarkerHighlightUpdated( AFGPlayerState* fgPlayerState, UFGActorRepresentation* actorRepresentation, bool highlighted){ }
void AFGMapManager::HighlightMapMarkerInstance( UHierarchicalInstancedStaticMeshComponent* component, int32 instanceIndex, bool highlighted, FLinearColor color){ }
void AFGMapManager::OnSetHighLightMarker( AFGPlayerState* fgPlayerState, UFGActorRepresentation* actorRepresentation){ }
void AFGMapManager::OnSetHighLightMarker(class AFGPlayerState* fgPlayerState, FGuid markerGUID){  }
UStaticMeshComponent* AFGMapManager::SpawnHighLightMarkerMeshComp(){ return nullptr; }
UNiagaraComponent* AFGMapManager::SpawnHighLightMarkerNiagaraComponent(const FVector& location){ return nullptr; }
void AFGMapManager::SyncSetHighLightMarker( AFGPlayerState* fgPlayerState, UFGActorRepresentation* actorRepresentation){ }
UFGHighlightedMarker* AFGMapManager::GetHighlightedActorRepresentation(const  AFGPlayerState* fgPlayerState) const{ return nullptr; }
bool AFGMapManager::IsActorRepresentationHighlighted(const UFGActorRepresentation* actorRepresentation, FLinearColor& out_HighlightColor, bool& out_HighlightByLocalPlayer) const{ return bool(); }
void AFGMapManager::UpdateHoveredMapMarker(const FHitResult& hitResult){ }
void AFGMapManager::SetMapMarkerHovered(TPair<  UHierarchicalInstancedStaticMeshComponent*, int32> instancedMeshPair, bool enabled){ }
void AFGMapManager::ClearHoveredMapMarker(){ }
void AFGMapManager::MapToHighlightedMarker(UFGActorRepresentation* actorRepresentation){ }
void AFGMapManager::UpdateFogOfWarRawData(const TArray<uint8>& newFogOfWarRawData){  }
void AFGMapManager::ReplaceFogOfWarData(uint8 newFogOfWarData){  }
void AFGMapManager::SetupFogOfWarTexture(){ }
void AFGMapManager::SetupRepresentationManager(){ }
void AFGMapManager::BindActorRepresentationManager( AFGActorRepresentationManager* representationManager){ }
void AFGMapManager::UpdateFogOfWar(UFGActorRepresentation* actor){ }
FVector2D AFGMapManager::GetMapPositionFromWorldLocation(FVector worldLocation){ return FVector2D(); }
float AFGMapManager::GetMapDistanceFromWorldDistance(float worldDistance){ return float(); }
void AFGMapManager::DrawCircle(FVector2D centerPoint, float radius, float gradientHeightModifier, bool useGradientFalloff){ }
void AFGMapManager::OnActorRepresentationAdded( UFGActorRepresentation* actorRepresentation){ }
void AFGMapManager::OnActorRepresentationUpdated( UFGActorRepresentation* actorRepresentation){ }
void AFGMapManager::OnActorRepresentationFOWUpdated( UFGActorRepresentation* actorRepresentation){ }
void AFGMapManager::OnActorRepresentationRemoved( UFGActorRepresentation* actorRepresentation){ }
void AFGMapManager::OnPlayerStateSlotDataUpdated( AFGPlayerState* playerState){ }
void AFGMapManager::RecreateSavedMarkers(){ }
void AFGMapManager::RefreshHighlightedMarkers(){ }
void AFGMapManager::Local_CreateOrUpdateMarkerRepresentation(const FMapMarker& mapMarker){  }
void AFGMapManager::Local_RemoveMarkerRepresentationById(const FGuid& markerGuid){  }
void AFGMapManager::CreateMapMarkersForInitialReplication(){  }
void AFGMapManager::Multicast_RemoveMapMarker_Implementation(const FGuid& mapMarkerGUID){  }
void AFGMapManager::Multicast_CreateUpdateMapMarker_Implementation(const FMapMarker& mapMarker){  }
void FFogOfWarWorker::DoWork(){ }
void FFogOfWarTask::DoWork(){ }
FFogOfWarTask::~FFogOfWarTask(){ }
