// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGNetworkLibrary.h"

bool UFGNetworkLibrary::OpenWebURL(const FString& Url){ return bool(); }
bool UFGNetworkLibrary::SubmitFeedback(FUserFeedbackFrontEndData frontEndFeedbackData,  APlayerController* playerController){ return bool(); }
