// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGNobeliskExplosive.h"

AFGNobeliskExplosive::AFGNobeliskExplosive(){ }
void AFGNobeliskExplosive::GetLifetimeReplicatedProps( TArray< FLifetimeProperty >& OutLifetimeProps) const{ }
void AFGNobeliskExplosive::OnImpact( const FHitResult& hitResult){ }
float AFGNobeliskExplosive::TakeDamage( float DamageAmount,  FDamageEvent const& DamageEvent,  AController* EventInstigator, AActor* DamageCauser){ return float(); }
bool AFGNobeliskExplosive::ShouldSave_Implementation() const{ return bool(); }
bool AFGNobeliskExplosive::NeedTransform_Implementation(){ return bool(); }
void AFGNobeliskExplosive::SetToDetonate( float timeUntilDetonate){ }
void AFGNobeliskExplosive::OnRep_DetonateIn(){ }
void AFGNobeliskExplosive::SetAndEnableRotation( float scale){ }
