// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGPhotoModeWidget.h"

UFGPhotoModeWidget::UFGPhotoModeWidget(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) {
	this->bIsFocusable = true;
}
void UFGPhotoModeWidget::NativeConstruct(){ }
void UFGPhotoModeWidget::NativeDestruct(){ }
void UFGPhotoModeWidget::ListenForInput(FInputChord inputkeyChord, TEnumAsByte<EInputEvent> eventType, bool consume, FOnInputAction callback){ }
void UFGPhotoModeWidget::StopListeningForAllInputs(){ }
void UFGPhotoModeWidget::ToggleMouseControl(){ }
void UFGPhotoModeWidget::ToggleAdvancedPhotoMode(){ }
void UFGPhotoModeWidget::TogglePhotoModeDebug(){ }
void UFGPhotoModeWidget::ListenForInputActionHelper(FInputChord inputkeyChord, bool consume, FOnInputAction pressedCallback, FOnInputAction releasedCallback, FOnInputAction doubleClickCallback){ }
