// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGPlayerStartTradingPost.h"

AFGPlayerStartTradingPost::AFGPlayerStartTradingPost(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) { }
const FName AFGPlayerStartTradingPost::STATIC_PLAYER_START_TAG = FName();
