// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGRadioactiveActor.h"
#include "Components/SceneComponent.h"

AFGRadioactiveActor::AFGRadioactiveActor() : Super() {
	this->mRadioactiveDecay = 0.0;
	this->RootComponent = CreateDefaultSubobject<USceneComponent>(TEXT("RootComponent"));
	this->RootComponent->SetMobility(EComponentMobility::Static);
}
void AFGRadioactiveActor::BeginPlay(){ Super::BeginPlay(); }
