// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGRailroadVehicleSoundComponent.h"

UFGRailroadVehicleSoundComponent::UFGRailroadVehicleSoundComponent(){ }
void UFGRailroadVehicleSoundComponent::OnRegister(){ Super::OnRegister(); }
void UFGRailroadVehicleSoundComponent::OnUnregister(){ Super::OnUnregister(); }
void UFGRailroadVehicleSoundComponent::TickComponent(float deltaTime, ELevelTick tickType, FActorComponentTickFunction* thisTickFunction){ }
void UFGRailroadVehicleSoundComponent::RestartSounds_Implementation(){ }
UFGRailroadVehicleMovementComponent* UFGRailroadVehicleSoundComponent::GetCachedMovementComponent(){ return nullptr; }
