// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGResourceNodeRepresentation.h"

UFGResourceNodeRepresentation::UFGResourceNodeRepresentation() : Super() {
	this->mResourceNode = nullptr;
	this->mIsStatic = true;
	this->mShouldShowOnMap = true;
}
void UFGResourceNodeRepresentation::SetupActorRepresentation(AActor* realActor, bool isLocal, float lifeSpan){ }
void UFGResourceNodeRepresentation::SetupResourceNodeRepresentation( AFGResourceNodeBase* resourceNode){ }
bool UFGResourceNodeRepresentation::IsCluster() const{ return bool(); }
bool UFGResourceNodeRepresentation::IsOccupied() const{ return bool(); }
