// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGResourceNodeGeyser.h"

AFGResourceNodeGeyser::AFGResourceNodeGeyser() : Super() {

}
void AFGResourceNodeGeyser::BeginPlay(){ Super::BeginPlay(); }
