// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGSaveInterface.h"

UFGSaveInterface::UFGSaveInterface(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) {}
