// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGSaveManagerInterface.h"

FSaveHeader::FSaveHeader(){ }
bool FSaveHeader::NetSerialize(FArchive& ar,  UPackageMap* map, bool& out_success){ return bool(); }
void IFGSaveManagerInterface::UploadSave(const FSaveHeader& Save, FOnSaveManagerTransferCompleted CompleteDelegate, FOnSaveManagerTransferProgress ProgressDelegate){ }
void IFGSaveManagerInterface::DownloadSave(const FSaveHeader& SaveGame, FOnSaveManagerTransferCompleted CompleteDelegate, FOnSaveManagerTransferProgress ProgressDelegate){ }
bool IFGSaveManagerInterface::IsTransferInProgress() const{ return bool(); }
void IFGSaveManagerInterface::BindOnSavesChanged(const FOnSaveManagerRefreshSaves& OnRefreshSaves){ }
void IFGSaveManagerInterface::UnbindOnSavesChanged(const FOnSaveManagerRefreshSaves& OnRefreshSaves){ }
