// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGSignificanceManager.h"

void FSignificanceOctreeSemantics::SetElementId(FOctree& Octree, const FSignificanceOctreeElement& Element, FOctreeElementId2 OctreeElementID){ }
UFGServerSideSignificanceSubsystem::UFGServerSideSignificanceSubsystem() : Super() {

}
bool UFGServerSideSignificanceSubsystem::DoesSupportWorldType(const EWorldType::Type WorldType) const{ return Super::DoesSupportWorldType(WorldType); }
void UFGServerSideSignificanceSubsystem::Tick(float DeltaTime){ Super::Tick(DeltaTime); }
TStatId UFGServerSideSignificanceSubsystem::GetStatId() const{ return TStatId(); }
void UFGServerSideSignificanceSubsystem::AddObjectToSignificanceOctTree(UObject* Object){ }
void UFGServerSideSignificanceSubsystem::RemoveObjectFromSignificanceOctTree(UObject* Object){ }
void UFGServerSideSignificanceSubsystem::ManuallyMarkObjectSignificant(UObject* Object){ }
FStaticSignificanceRegistrationInfo UFGSignificanceManager::GetStaticObjectInfo(const UObject* Object) const{ return Super::GetStaticObjectInfo(Object); }
FStaticObjectSignificanceUpdateInfo UFGSignificanceManager::GetDynamicObjectInfo(const UObject* Object) const{ return Super::GetDynamicObjectInfo(Object); }
void UFGSignificanceManager::OnSignificanceLoss(UObject* Object){ Super::OnSignificanceLoss(Object); }
void UFGSignificanceManager::OnSignificanceGain(UObject* Object){ Super::OnSignificanceGain(Object); }
void UFGSignificanceManager::OnSignificanceTickRateUpdate(UObject* Object, int32 TickLevel, int32 NumTickLevels){ }
void UFGSignificanceManager::SetInitialSignificanceState(UObject* Object, bool bState){ Super::SetInitialSignificanceState(Object, bState); }
FBox UFGSignificanceManager::CalculateObjectBoundingBox(const UObject* Element){ return FBox(); }
