// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGStoryQueue.h"

TArray< TSubclassOf< class UFGMessageBase > > UFGStoryQueue::GetMessages(TSubclassOf< UFGStoryQueue > inClass){ return TArray<TSubclassOf<class UFGMessageBase> >(); }
bool UFGStoryQueue::IsMessageTriggeredByMilestone(TSubclassOf< UFGStoryQueue > inClass){ return bool(); }
float UFGStoryQueue::GetDelayAfterMilestone(TSubclassOf< UFGStoryQueue > inClass){ return float(); }
bool UFGStoryQueue::IsMessageTriggeredByTimer(TSubclassOf< UFGStoryQueue > inClass){ return bool(); }
float UFGStoryQueue::GetTimeUntilMessageIsTriggered(TSubclassOf< UFGStoryQueue > inClass){ return float(); }
float UFGStoryQueue::GetMinimumDelayBetweenMessages(TSubclassOf< UFGStoryQueue > inClass){ return float(); }
float UFGStoryQueue::GetMaximumDelayForCall(TSubclassOf< UFGStoryQueue > inClass){ return float(); }
TArray< FEventTriggeredMessage > UFGStoryQueue::GetFloatingMessages(TSubclassOf< UFGStoryQueue > inClass){ return TArray<FEventTriggeredMessage>(); }
bool UFGStoryQueue::AreDependenciesForQueueMet(TSubclassOf< UFGStoryQueue > inClass, UObject* worldContext){ return bool(); }
void UFGStoryQueue::GetStoryQueueDebugData(TSubclassOf< UFGStoryQueue > inClass, TArray<FString>& out_debugData){ }
