// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGSubsystemClasses.h"
#include "FGLightweightBuildableSubsystem.h"

UFGSubsystemClasses::UFGSubsystemClasses() : Super() {
	this->mStorySubsystemClass = FSoftClassPath("/Game/FactoryGame/-Shared/Blueprint/BP_StorySubsystem.BP_StorySubsystem_C");
	this->mTimeSubsystemClass = FSoftClassPath("/Game/FactoryGame/-Shared/Blueprint/BP_TimeOfDaySubsystem.BP_TimeOfDaySubsystem_C");
	this->mRailroadSubsystemClass = FSoftClassPath("/Game/FactoryGame/-Shared/Blueprint/BP_RailroadSubsystem.BP_RailroadSubsystem_C");
	this->mCircuitSubsystemClass = FSoftClassPath("/Game/FactoryGame/-Shared/Blueprint/BP_CircuitSubsystem.BP_CircuitSubsystem_C");
	this->mSchematicManagerClass = FSoftClassPath("/Game/FactoryGame/Schematics/Progression/BP_SchematicManager.BP_SchematicManager_C");
	this->mGamePhaseManagerClass = FSoftClassPath("/Game/FactoryGame/Schematics/Progression/BP_GamePhaseManager.BP_GamePhaseManager_C");
	this->mResearchManagerClass = FSoftClassPath("/Game/FactoryGame/Recipes/Research/BP_ResearchManager.BP_ResearchManager_C");
	this->mTutorialIntroManagerClass = FSoftClassPath("/Game/FactoryGame/-Shared/Blueprint/BP_TutorialIntroManager.BP_TutorialIntroManager_C");
	this->mRadioactivitySubsystemClass = FSoftClassPath("/Game/FactoryGame/-Shared/Blueprint/BP_RadioactiveSubsystem.BP_RadioactiveSubsystem_C");
	this->mChatManagerClass = FSoftClassPath("/Game/FactoryGame/-Shared/Blueprint/BP_ChatManager.BP_ChatManager_C");
	this->mCentralStorageSubsystemClass = FSoftClassPath("/Script/FactoryGame.FGCentralStorageSubsystem");
	this->mMapManagerClass = FSoftClassPath("/Script/FactoryGame.FGMapManager");
	this->mBuildableSubsystemClass = FSoftClassPath("/Game/FactoryGame/-Shared/Blueprint/BP_BuildableSubsystem.BP_BuildableSubsystem_C").ResolveClass();
	this->mLightweightBuildableSubsystemClass = AFGLightweightBuildableSubsystem::StaticClass();
	this->mFoliageRemovalSubsystemClass = FSoftClassPath("/Script/FactoryGame.FGFoliageRemovalSubsystem");
	this->mProximitySubsystemClass = FSoftClassPath("/Game/FactoryGame/Character/Player/BP_ProximitySubsystem.BP_ProximitySubsystem_C");
	this->mUnlockSubsystem = FSoftClassPath("/Game/FactoryGame/Unlocks/BP_UnlockSubsystem.BP_UnlockSubsystem_C");
	this->mResourceSinkSubsystemClass = FSoftClassPath("/Script/FactoryGame.FGResourceSinkSubsystem");
	this->mAdminInterfaceClass = FSoftClassPath("/Script/FactoryGame.FGAdminInterface");
	this->mItemRegrowSubsystemClass = FSoftClassPath("/Script/FactoryGame.FGItemRegrowSubsystem");
	this->mVehicleSubsystemClass = FSoftClassPath("/Game/FactoryGame/-Shared/Blueprint/BP_VehicleSubsystem.BP_VehicleSubsystem_C");
	this->mEventSubsystemClass = FSoftClassPath("/Game/FactoryGame/Events/BP_EventSubsystem.BP_EventSubsystem_C");
	this->mWorldGridSubsystemClass = FSoftClassPath("/Game/FactoryGame/-Shared/Blueprint/BP_WorldGridSubsystem.BP_WorldGridSubsystem_C");
	this->mDroneSubsystemClass = FSoftClassPath("/Game/FactoryGame/-Shared/Blueprint/BP_DroneSubsystem.BP_DroneSubsystem_C");
	this->mConveyorItemSubsystemClass = FSoftClassPath("/Game/FactoryGame/-Shared/Blueprint/BP_ConveyorItemSubsystem.BP_ConveyorItemSubsystem_C");
	this->mStatisticsSubsystemClass = FSoftClassPath("/Script/FactoryGame.FGStatisticsSubsystem");
	this->mSignSubsystemClass = FSoftClassPath("/Script/FactoryGame.FGSignSubsystem");
	this->mPhotoModeManagerClass = FSoftClassPath("/Script/FactoryGame.FGPhotoModeManager");
	this->mCreatureSubsystemClass = FSoftClassPath("/Game/FactoryGame/-Shared/Blueprint/BP_CreatureSubsystem.BP_CreatureSubsystem_C");
	this->mScannableSubsystemClass = FSoftClassPath("/Script/FactoryGame.FGScannableSubsystem");
	this->mBlueprintSubsystem = FSoftClassPath("/Game/FactoryGame/-Shared/Blueprint/BP_BlueprintSusbystem.BP_BlueprintSusbystem_C");
	this->mIconDatabaseSubsystem = FSoftClassPath("/Game/FactoryGame/-Shared/Blueprint/BP_IconDatabaseSubsystem.BP_IconDatabaseSubsystem_C");
	this->mWorldEventSubsystem = FSoftClassPath("/Script/FactoryGame.FGWorldEventSubsystem");
}
