// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGVehicleCollisionBoxComponent.h"

UFGVehicleCollisionBoxComponent::UFGVehicleCollisionBoxComponent(){ }
void UFGVehicleCollisionBoxComponent::OnOverlapBegin( UPrimitiveComponent* OverlappedComp, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult){ }
void UFGVehicleCollisionBoxComponent::PushCharacter( AActor* OtherActor){ }
