// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGVehicleSubsystem.h"

AFGVehicleSubsystem::AFGVehicleSubsystem(){ }
void AFGVehicleSubsystem::Tick(float dt){ }
AFGVehicleSubsystem* AFGVehicleSubsystem::Get(UWorld* world){ return nullptr; }
AFGVehicleSubsystem* AFGVehicleSubsystem::Get(UObject* worldContext){ return nullptr; }
void AFGVehicleSubsystem::TickVehicleSimulation(float dt){ }
float AFGVehicleSubsystem::FindClosestPlayerSq( AActor* actor) const{ return float(); }
void AFGVehicleSubsystem::AddVehicle( AFGVehicle* vehicle){ }
void AFGVehicleSubsystem::RemoveVehicle( AFGVehicle* vehicle){ }
