// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGWeatherReaction.h"
#include "Net/UnrealNetwork.h"

AFGWeatherReaction::AFGWeatherReaction() : Super() {
	this->TransitionTime = 30.0;
	this->mCurrentState = EWeatherInterpState::EWeatherInterpState_Undefined;
	this->mSkySphere = nullptr;
	this->PrimaryActorTick.TickGroup = ETickingGroup::TG_PrePhysics;
	this->PrimaryActorTick.EndTickGroup = ETickingGroup::TG_PrePhysics;
	this->PrimaryActorTick.bTickEvenWhenPaused = false;
	this->PrimaryActorTick.bCanEverTick = true;
	this->PrimaryActorTick.bStartWithTickEnabled = false;
	this->PrimaryActorTick.bAllowTickOnDedicatedServer = true;
	this->PrimaryActorTick.TickInterval = 0.0;
	this->bAlwaysRelevant = true;
	this->bReplicates = true;
}
void AFGWeatherReaction::Tick(float DeltaSeconds){ Super::Tick(DeltaSeconds); }
void AFGWeatherReaction::BeginPlay(){ Super::BeginPlay(); }
void AFGWeatherReaction::EndPlay(const EEndPlayReason::Type EndPlayReason){ Super::EndPlay(EndPlayReason); }
void AFGWeatherReaction::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const {
	Super::GetLifetimeReplicatedProps(OutLifetimeProps);
	DOREPLIFETIME(AFGWeatherReaction, mCurrentState);
}
void AFGWeatherReaction::ServerBeginWeatherState(){ }
void AFGWeatherReaction::ServerFinishedEnterState(){ }
void AFGWeatherReaction::ServerEndWeatherState(){ }
void AFGWeatherReaction::OnTransitionFinished_Implementation(bool bEventFinished){ }
void AFGWeatherReaction::OnRep_OnStateUpdated(EWeatherInterpState OldState){ }
void AFGWeatherReaction::StartWeatherState_Implementation(AFGSkySphere* SkySphere){ }
void AFGWeatherReaction::EndWeatherState_Implementation(AFGSkySphere* SkySphere){ }
