// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGWorldScannableData.h"

FWorldScannableData::FWorldScannableData(AActor* actor){ }
#if WITH_EDITOR
void UFGWorldScannableData::GenerateWorldScannableData(UWorld* world){ }
#endif 
#if WITH_EDITOR
void AFGWorldScannableDataGenerator::GenerateWorldScannableData(){ }
#endif 
AFGWorldScannableDataGenerator::AFGWorldScannableDataGenerator() : Super() {

}
