// This file has been automatically generated by the Unreal Header Implementation tool

#include "Hologram/FGCornerWallHologram.h"
#include "AkAudio/Classes/AkComponent.h"
#include "Components/SceneComponent.h"

AFGCornerWallHologram::AFGCornerWallHologram() : Super() {

}
void AFGCornerWallHologram::BeginPlay(){ }
bool AFGCornerWallHologram::TrySnapToActor(const FHitResult& hitResult){ return bool(); }
