// This file has been automatically generated by the Unreal Header Implementation tool

#include "Hologram/FGFactoryHologram.h"
#include "Buildables/FGBuildableRoad.h"
#include "Buildables/FGBuildableRailroadTrack.h"
#include "Buildables/FGBuildableFoundation.h"

AFGFactoryHologram::AFGFactoryHologram() : Super() {
	this->mMaxPlacementFloorAngle = 35;
	this->mValidHitClasses.Add(AFGBuildableFoundation::StaticClass()); this->mValidHitClasses.Add(AFGBuildableRailroadTrack::StaticClass()); this->mValidHitClasses.Add(AFGBuildableRoad::StaticClass());
	this->mUseBuildClearanceOverlapSnapp = true;
	this->SetHidden(true);
	this->SetReplicates(true);
}
void AFGFactoryHologram::BeginPlay(){ }
void AFGFactoryHologram::Tick(float dt){ }
void AFGFactoryHologram::SetupClearance( UBoxComponent* boxComponent){ }
void AFGFactoryHologram::SetHologramLocationAndRotation(const FHitResult& hitResult){ }
void AFGFactoryHologram::Destroyed(){ }
FVector AFGFactoryHologram::GetGuideLinesBaseLocation(){ return FVector(); }
