// This file has been automatically generated by the Unreal Header Implementation tool

#include "Hologram/FGPipeReservoirHologram.h"

AFGPipeReservoirHologram::AFGPipeReservoirHologram() : Super() {

}
void AFGPipeReservoirHologram::BeginPlay(){ }
bool AFGPipeReservoirHologram::IsValidHitResult(const FHitResult& hitResult) const{ return bool(); }
bool AFGPipeReservoirHologram::TrySnapToActor(const FHitResult& hitResult){ return bool(); }
int32 AFGPipeReservoirHologram::GetRotationStep() const{ return int32(); }
