// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGPipelineJunctionHologram.h"

AFGPipelineJunctionHologram::AFGPipelineJunctionHologram(){ }
void AFGPipelineJunctionHologram::SetHologramLocationAndRotation( const FHitResult& hitResult){ }
int32 AFGPipelineJunctionHologram::GetRotationStep() const{ return int32(); }
