// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGPoleHologram.h"

AFGPoleHologram::AFGPoleHologram(){ }
void AFGPoleHologram::GetLifetimeReplicatedProps( TArray< FLifetimeProperty >& OutLifetimeProps) const{ }
void AFGPoleHologram::BeginPlay(){ }
bool AFGPoleHologram::MultiStepPlacement(){ return bool(); }
bool AFGPoleHologram::IsValidHitResult( const FHitResult& hitResult) const{ return bool(); }
bool AFGPoleHologram::TrySnapToActor( const FHitResult& hitResult){ return bool(); }
void AFGPoleHologram::SetHologramLocationAndRotation( const FHitResult& hitResult){ }
void AFGPoleHologram::CheckClearance(){ }
bool AFGPoleHologram::CheckClearanceForBuildingMesh( UStaticMeshComponent* mesh, const FComponentQueryParams& params ){ return bool(); }
void AFGPoleHologram::SetPoleHeight( float height){ }
void AFGPoleHologram::ConfigureActor(  AFGBuildable* inBuildable) const{ }
void AFGPoleHologram::OnRep_PoleMesh(){ }
void AFGPoleHologram::UpdatePoleHeightRelativeLoc(){ }
