// This file has been automatically generated by the Unreal Header Implementation tool

#include "Hologram/FGRailroadSwitchControlHologram.h"

void AFGRailroadSwitchControlHologram::SetHologramLocationAndRotationFromConnection( UFGRailroadTrackConnectionComponent* controlledConnection){ }
void AFGRailroadSwitchControlHologram::ConfigureActor( AFGBuildable* inBuildable) const{ }
