// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGWallHologram.h"

AFGWallHologram::AFGWallHologram(){ }
void AFGWallHologram::BeginPlay(){ }
bool AFGWallHologram::TrySnapToActor( const FHitResult& hitResult){ return bool(); }
int32 AFGWallHologram::GetRotationStep() const{ return int32(); }
