// This file has been automatically generated by the Unreal Header Implementation tool

#include "Hologram/FGWheeledVehicleHologram.h"

void AFGWheeledVehicleHologram::HandleClearanceOverlap(const FOverlapResult& overlap, const FVector& locationOffset, bool HologramHasSoftClearance){ }
void AFGWheeledVehicleHologram::SetHologramLocationAndRotation(const FHitResult& hitResult){ }
AFGVehicle* AFGWheeledVehicleHologram::ConstructVehicle(FNetConstructionID netConstructionID) const{ return nullptr; }
