// This file has been automatically generated by the Unreal Header Implementation tool

#include "Online/Widgets/FGJoinListEntry.h"

void UFGJoinListEntry::PresenceUpdated(const  UOnlineFriend* friendObject){ }
void UFGJoinListEntry::NativeOnListItemObjectSet(UObject* ListItemObject){ }
void UFGJoinListEntry::NativeOnEntryReleased(){ }
void UFGJoinListEntry::NativeOnItemSelectionChanged(bool bIsSelected){ }
bool UFGJoinListEntry::IsListItemSelectable() const{ return bool(); }
