// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGBuildableTrainPlatformCargo.h"

AFGBuildableTrainPlatformCargo::AFGBuildableTrainPlatformCargo(){ }
void AFGBuildableTrainPlatformCargo::GetLifetimeReplicatedProps( TArray<FLifetimeProperty>& OutLifetimeProps) const{ }
void AFGBuildableTrainPlatformCargo::BeginPlay(){ }
void AFGBuildableTrainPlatformCargo::Destroyed(){ }
bool AFGBuildableTrainPlatformCargo::Dock(  AFGRailroadVehicle* actor){ return bool(); }
void AFGBuildableTrainPlatformCargo::Undock(){ }
void AFGBuildableTrainPlatformCargo::SetIsInLoadMode( bool isInLoadMode){ }
bool AFGBuildableTrainPlatformCargo::GetIsInLoadMode() const{ return bool(); }
bool AFGBuildableTrainPlatformCargo::IsLoadUnloading() const{ return bool(); }
float AFGBuildableTrainPlatformCargo::GetDockedVehicleOffset() const{ return float(); }
void AFGBuildableTrainPlatformCargo::RegisteredOnTrack_Implementation( const FRailroadTrackPosition& position){ }
void AFGBuildableTrainPlatformCargo::UnregisteredFromTrack_Implementation(){ }
FRailroadTrackPosition AFGBuildableTrainPlatformCargo::GetTrackPosition_Implementation() const{ return FRailroadTrackPosition(); }
int32 AFGBuildableTrainPlatformCargo::GetTrackGraphID_Implementation() const{ return int32(); }
bool AFGBuildableTrainPlatformCargo::ShouldRegisterOnTrack(){ return bool(); }
void AFGBuildableTrainPlatformCargo::NotifyTrainDocked(  AFGRailroadVehicle* railroadVehicle,  AFGBuildableRailroadStation* initiatedByStation){ }
void AFGBuildableTrainPlatformCargo::UpdateDockingSequence(){ }
void AFGBuildableTrainPlatformCargo::UpdatePowerConnectionFromTrack(){ }
void AFGBuildableTrainPlatformCargo::Factory_Tick( float dt){ }
void AFGBuildableTrainPlatformCargo::Factory_TickProducing( float dt){ }
void AFGBuildableTrainPlatformCargo::Factory_CollectInput_Implementation(){ }
bool AFGBuildableTrainPlatformCargo::CanProduce_Implementation() const{ return bool(); }
void AFGBuildableTrainPlatformCargo::OnRep_ReplicationDetailActor(){ }
void AFGBuildableTrainPlatformCargo::OnRep_UpdateDockingStatus(){ }
int32 AFGBuildableTrainPlatformCargo::GetFirstIndexWithItem( UFGInventoryComponent* inventory){ return int32(); }
void AFGBuildableTrainPlatformCargo::Factory_TransferInventoryToTrain(){ }
void AFGBuildableTrainPlatformCargo::Factory_TransferInventoryToPlatform(){ }
void AFGBuildableTrainPlatformCargo::LoadUnloadVehicleComplete(){ }
void AFGBuildableTrainPlatformCargo::CheckCanPerformFullUnload(){ }
void AFGBuildableTrainPlatformCargo::CheckCanPerformFullLoad(){ }
void AFGBuildableTrainPlatformCargo::SwapCargoContainerVisibility(){ }
void AFGBuildableTrainPlatformCargo::HidePlatformCargoContainer(){ }
void AFGBuildableTrainPlatformCargo::ShowPlatformCargoContainer(){ }
void AFGBuildableTrainPlatformCargo::OnCargoPowerStateChanged( bool hasPower){ }
FName AFGBuildableTrainPlatformCargo::mMagicBoxComponentName = FName();
FName AFGBuildableTrainPlatformCargo::mCargoMeshComponentName = FName();
