// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGBuildableTrainPlatform.h"

AFGBuildableTrainPlatform::AFGBuildableTrainPlatform(){ }
void AFGBuildableTrainPlatform::GetLifetimeReplicatedProps( TArray<FLifetimeProperty>& OutLifetimeProps) const{ }
void AFGBuildableTrainPlatform::PreSaveGame_Implementation( int32 saveVersion, int32 gameVersion){ }
void AFGBuildableTrainPlatform::PostLoadGame_Implementation( int32 saveVersion, int32 gameVersion){ }
bool AFGBuildableTrainPlatform::CanDismantle_Implementation() const{ return bool(); }
void AFGBuildableTrainPlatform::Dismantle_Implementation(){ }
void AFGBuildableTrainPlatform::GetDismantleRefund_Implementation( TArray< FInventoryStack >& out_refund) const{ }
bool AFGBuildableTrainPlatform::IsUseable_Implementation() const{ return bool(); }
AFGBuildableTrainPlatform* AFGBuildableTrainPlatform::GetConnectedPlatformInDirectionOf( uint8 direction){ return nullptr; }
void AFGBuildableTrainPlatform::AssignChildTrackBuildable(  AFGBuildableRailroadTrack* railroadTrack){ }
AFGBuildableRailroadTrack* AFGBuildableTrainPlatform::GetChildTrackBuildable(){ return nullptr; }
TArray<class UFGTrainPlatformConnection*> AFGBuildableTrainPlatform::GetPlatformConnectionComponents(){ return TArray<class UFGTrainPlatformConnection*>(); }
bool AFGBuildableTrainPlatform::ShouldRegisterOnTrack(){ return bool(); }
void AFGBuildableTrainPlatform::ReverseConnectionDirections(){ }
void AFGBuildableTrainPlatform::NotifyTrainDocked(  AFGRailroadVehicle* railroadVehicle,  AFGBuildableRailroadStation* initiaedByStation){ }
void AFGBuildableTrainPlatform::UpdateDockingSequence(){ }
void AFGBuildableTrainPlatform::FinishDockingSequence(){ }
void AFGBuildableTrainPlatform::OnRep_UpdateDockingStatus(){ }
