// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGDotComponent.h"

#if WITH_EDITOR
void UFGDotComponent::CheckForErrors(){ }
#endif 
UFGDotComponent::UFGDotComponent(){ }
void UFGDotComponent::PostLoad(){ Super::PostLoad(); }
void UFGDotComponent::OnRegister(){ Super::OnRegister(); }
void UFGDotComponent::OnUnregister(){ Super::OnUnregister(); }
void UFGDotComponent::Activate( bool reset ){ }
void UFGDotComponent::Deactivate(){ }
void UFGDotComponent::StartDamageTimer(){ }
void UFGDotComponent::OnPrimitiveComponentEntered( UPrimitiveComponent* overlappedComp, AActor* other, UPrimitiveComponent* otherComp, int32 otherBodyIndex, bool fromSweep, const FHitResult& sweepResult){ }
void UFGDotComponent::OnPrimitiveComponentExited( UPrimitiveComponent* overlappedComp, AActor* other, UPrimitiveComponent* otherComp, int32 otherBodyIndex){ }
void UFGDotComponent::DamageContainingActors(){ }
