#pragma once

// Satisfactory SDK (V0.1.13 - Build 99427)

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "FG_Anim_NonFlyingBird_classes.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function Anim_NonFlyingBird.Anim_NonFlyingBird_C.CalculateAnimGraphVariables
struct UAnim_NonFlyingBird_C_CalculateAnimGraphVariables_Params
{
};

// Function Anim_NonFlyingBird.Anim_NonFlyingBird_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_ModifyBone_05C126F44A9F16648DD6B388F6C33A5F
struct UAnim_NonFlyingBird_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_ModifyBone_05C126F44A9F16648DD6B388F6C33A5F_Params
{
};

// Function Anim_NonFlyingBird.Anim_NonFlyingBird_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_ModifyBone_5F52D0D14937CA30159422BA55A5C718
struct UAnim_NonFlyingBird_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_ModifyBone_5F52D0D14937CA30159422BA55A5C718_Params
{
};

// Function Anim_NonFlyingBird.Anim_NonFlyingBird_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_ModifyBone_36FB95424048EBDEEAC525B07E5E3591
struct UAnim_NonFlyingBird_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_ModifyBone_36FB95424048EBDEEAC525B07E5E3591_Params
{
};

// Function Anim_NonFlyingBird.Anim_NonFlyingBird_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_BlendListByBool_92E64BBF4C6123CFB9F2F8AE835DA27C
struct UAnim_NonFlyingBird_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_BlendListByBool_92E64BBF4C6123CFB9F2F8AE835DA27C_Params
{
};

// Function Anim_NonFlyingBird.Anim_NonFlyingBird_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_ModifyBone_0EDC6F76461CF802C87BD68CBEA926B1
struct UAnim_NonFlyingBird_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_ModifyBone_0EDC6F76461CF802C87BD68CBEA926B1_Params
{
};

// Function Anim_NonFlyingBird.Anim_NonFlyingBird_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_ModifyBone_0FAEA1A64B563AA9612CEC83AFEB2B0D
struct UAnim_NonFlyingBird_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_ModifyBone_0FAEA1A64B563AA9612CEC83AFEB2B0D_Params
{
};

// Function Anim_NonFlyingBird.Anim_NonFlyingBird_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_BlendListByBool_DD12E8E64B1EA9C942E361862ECC6C53
struct UAnim_NonFlyingBird_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_BlendListByBool_DD12E8E64B1EA9C942E361862ECC6C53_Params
{
};

// Function Anim_NonFlyingBird.Anim_NonFlyingBird_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_ModifyBone_34B195164CD34B68146E62986D5CAF0A
struct UAnim_NonFlyingBird_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_ModifyBone_34B195164CD34B68146E62986D5CAF0A_Params
{
};

// Function Anim_NonFlyingBird.Anim_NonFlyingBird_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_BlendListByBool_F187D61B47A7B311D7C631B70507AC99
struct UAnim_NonFlyingBird_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_BlendListByBool_F187D61B47A7B311D7C631B70507AC99_Params
{
};

// Function Anim_NonFlyingBird.Anim_NonFlyingBird_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_TransitionResult_CA78DDEC4BFEB1C7E21681903550772B
struct UAnim_NonFlyingBird_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_TransitionResult_CA78DDEC4BFEB1C7E21681903550772B_Params
{
};

// Function Anim_NonFlyingBird.Anim_NonFlyingBird_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_TransitionResult_E2E2D2C3420B0B118E0C66BB7D9FAD61
struct UAnim_NonFlyingBird_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_TransitionResult_E2E2D2C3420B0B118E0C66BB7D9FAD61_Params
{
};

// Function Anim_NonFlyingBird.Anim_NonFlyingBird_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_BlendSpacePlayer_8691C78B41CE7191E40E159A06D14AFE
struct UAnim_NonFlyingBird_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_BlendSpacePlayer_8691C78B41CE7191E40E159A06D14AFE_Params
{
};

// Function Anim_NonFlyingBird.Anim_NonFlyingBird_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_TransitionResult_1D36264049ECD049E74B4B9C74039CF1
struct UAnim_NonFlyingBird_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_TransitionResult_1D36264049ECD049E74B4B9C74039CF1_Params
{
};

// Function Anim_NonFlyingBird.Anim_NonFlyingBird_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_TransitionResult_8DC639204057972E8F854D83719EB11B
struct UAnim_NonFlyingBird_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_TransitionResult_8DC639204057972E8F854D83719EB11B_Params
{
};

// Function Anim_NonFlyingBird.Anim_NonFlyingBird_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_TransitionResult_93F56C3644CD506A5E44A9B89733CE4D
struct UAnim_NonFlyingBird_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_TransitionResult_93F56C3644CD506A5E44A9B89733CE4D_Params
{
};

// Function Anim_NonFlyingBird.Anim_NonFlyingBird_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_TransitionResult_12D3EAA6436388A5BE8FE5ABE9EBA2D5
struct UAnim_NonFlyingBird_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_TransitionResult_12D3EAA6436388A5BE8FE5ABE9EBA2D5_Params
{
};

// Function Anim_NonFlyingBird.Anim_NonFlyingBird_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_TransitionResult_694A5C404254F451A9F9AFBDF84B9EB7
struct UAnim_NonFlyingBird_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_TransitionResult_694A5C404254F451A9F9AFBDF84B9EB7_Params
{
};

// Function Anim_NonFlyingBird.Anim_NonFlyingBird_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_TransitionResult_60BE805E4E0C482A65AABD803219B2BD
struct UAnim_NonFlyingBird_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_TransitionResult_60BE805E4E0C482A65AABD803219B2BD_Params
{
};

// Function Anim_NonFlyingBird.Anim_NonFlyingBird_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_TransitionResult_BF89D0C742A9E2A9E3DDF3B98FD51A81
struct UAnim_NonFlyingBird_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_TransitionResult_BF89D0C742A9E2A9E3DDF3B98FD51A81_Params
{
};

// Function Anim_NonFlyingBird.Anim_NonFlyingBird_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_TransitionResult_883AD7EF4BADD62F82C827926B28E8E3
struct UAnim_NonFlyingBird_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_TransitionResult_883AD7EF4BADD62F82C827926B28E8E3_Params
{
};

// Function Anim_NonFlyingBird.Anim_NonFlyingBird_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_TransitionResult_10926B584B7CDD4D1443AFAC460E066A
struct UAnim_NonFlyingBird_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_TransitionResult_10926B584B7CDD4D1443AFAC460E066A_Params
{
};

// Function Anim_NonFlyingBird.Anim_NonFlyingBird_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_TransitionResult_68EA3D054DB99A7474521BA4348F453A
struct UAnim_NonFlyingBird_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_TransitionResult_68EA3D054DB99A7474521BA4348F453A_Params
{
};

// Function Anim_NonFlyingBird.Anim_NonFlyingBird_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_TransitionResult_BDF1DFB547BC2081EF4765867D2165B4
struct UAnim_NonFlyingBird_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_TransitionResult_BDF1DFB547BC2081EF4765867D2165B4_Params
{
};

// Function Anim_NonFlyingBird.Anim_NonFlyingBird_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_TransitionResult_0126102A476E3DA76FB6EF8D310D64B3
struct UAnim_NonFlyingBird_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_TransitionResult_0126102A476E3DA76FB6EF8D310D64B3_Params
{
};

// Function Anim_NonFlyingBird.Anim_NonFlyingBird_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_TransitionResult_83711B374B983B85DAEE719C0900E946
struct UAnim_NonFlyingBird_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_TransitionResult_83711B374B983B85DAEE719C0900E946_Params
{
};

// Function Anim_NonFlyingBird.Anim_NonFlyingBird_C.OnRadialDamageTaken
struct UAnim_NonFlyingBird_C_OnRadialDamageTaken_Params
{
};

// Function Anim_NonFlyingBird.Anim_NonFlyingBird_C.OnPointDamageTaken
struct UAnim_NonFlyingBird_C_OnPointDamageTaken_Params
{
	struct FVector*                                    shootDIrection;                                           // (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData)
};

// Function Anim_NonFlyingBird.Anim_NonFlyingBird_C.AnimNotify_NFBEnteredIdleLuringState
struct UAnim_NonFlyingBird_C_AnimNotify_NFBEnteredIdleLuringState_Params
{
};

// Function Anim_NonFlyingBird.Anim_NonFlyingBird_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_TransitionResult_68DB26574E4C52578E6033994EC4068E
struct UAnim_NonFlyingBird_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_TransitionResult_68DB26574E4C52578E6033994EC4068E_Params
{
};

// Function Anim_NonFlyingBird.Anim_NonFlyingBird_C.AnimNotify_AnimNotify_NFB_Jump
struct UAnim_NonFlyingBird_C_AnimNotify_AnimNotify_NFB_Jump_Params
{
};

// Function Anim_NonFlyingBird.Anim_NonFlyingBird_C.AnimNotify_AnimNotify_NFB_Land
struct UAnim_NonFlyingBird_C_AnimNotify_AnimNotify_NFB_Land_Params
{
};

// Function Anim_NonFlyingBird.Anim_NonFlyingBird_C.AnimNotify_NFB_EnteredMoving
struct UAnim_NonFlyingBird_C_AnimNotify_NFB_EnteredMoving_Params
{
};

// Function Anim_NonFlyingBird.Anim_NonFlyingBird_C.AnimNotify_NFBLeftLuringState
struct UAnim_NonFlyingBird_C_AnimNotify_NFBLeftLuringState_Params
{
};

// Function Anim_NonFlyingBird.Anim_NonFlyingBird_C.AnimNotify_NFB_LeftMoving
struct UAnim_NonFlyingBird_C_AnimNotify_NFB_LeftMoving_Params
{
};

// Function Anim_NonFlyingBird.Anim_NonFlyingBird_C.AnimNotify_AnimNotify_NFB_VO_Long
struct UAnim_NonFlyingBird_C_AnimNotify_AnimNotify_NFB_VO_Long_Params
{
};

// Function Anim_NonFlyingBird.Anim_NonFlyingBird_C.BlueprintUpdateAnimation
struct UAnim_NonFlyingBird_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

// Function Anim_NonFlyingBird.Anim_NonFlyingBird_C.AnimNotify_AnimNotify_NFB_JumpLoop
struct UAnim_NonFlyingBird_C_AnimNotify_AnimNotify_NFB_JumpLoop_Params
{
};

// Function Anim_NonFlyingBird.Anim_NonFlyingBird_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_TransitionResult_87F75D2E4BFE8554532E9D9FBE5BBD90
struct UAnim_NonFlyingBird_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Anim_NonFlyingBird_AnimGraphNode_TransitionResult_87F75D2E4BFE8554532E9D9FBE5BBD90_Params
{
};

// Function Anim_NonFlyingBird.Anim_NonFlyingBird_C.ExecuteUbergraph_Anim_NonFlyingBird
struct UAnim_NonFlyingBird_C_ExecuteUbergraph_Anim_NonFlyingBird_Params
{
	int                                                EntryPoint;                                               // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
