#pragma once

// Satisfactory SDK (V0.1.13 - Build 99427)

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "FG_BP_SpaceRabbitAnim_classes.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.CalculateAnimGraphValues
struct UBP_SpaceRabbitAnim_C_CalculateAnimGraphValues_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_CFC24A3341A01FC2A0BB85AB340CE23F
struct UBP_SpaceRabbitAnim_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_CFC24A3341A01FC2A0BB85AB340CE23F_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_B80A8A354AA03D0F6BFD6D86D7388DC3
struct UBP_SpaceRabbitAnim_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_B80A8A354AA03D0F6BFD6D86D7388DC3_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_BlendListByBool_43B3EAFD4F87F786DE07419EE69FB884
struct UBP_SpaceRabbitAnim_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_BlendListByBool_43B3EAFD4F87F786DE07419EE69FB884_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_BlendSpacePlayer_E78CF619465F9C321B545384E19CCB02
struct UBP_SpaceRabbitAnim_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_BlendSpacePlayer_E78CF619465F9C321B545384E19CCB02_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_BlendListByBool_F15A1E54444B366DFADC9C8CB6317F91
struct UBP_SpaceRabbitAnim_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_BlendListByBool_F15A1E54444B366DFADC9C8CB6317F91_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_F28B95014E4ADEAF5E19A3B63949184C
struct UBP_SpaceRabbitAnim_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_F28B95014E4ADEAF5E19A3B63949184C_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_3ABE92444DBDEFC4AE09F68B8604F309
struct UBP_SpaceRabbitAnim_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_3ABE92444DBDEFC4AE09F68B8604F309_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_11E8210B4F2EB87DF2914DA75048E67F
struct UBP_SpaceRabbitAnim_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_11E8210B4F2EB87DF2914DA75048E67F_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_7E7CD9FB4C16CD648D14C8BFD84A080C
struct UBP_SpaceRabbitAnim_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_7E7CD9FB4C16CD648D14C8BFD84A080C_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_8B41F8DD40D8915E5B51338C0E7A6CC8
struct UBP_SpaceRabbitAnim_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_8B41F8DD40D8915E5B51338C0E7A6CC8_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_ECAE384A48840A166AE91DA38AB6D368
struct UBP_SpaceRabbitAnim_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_ECAE384A48840A166AE91DA38AB6D368_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_43A53F9C494FCBCB2CEFBE86C56DE89C
struct UBP_SpaceRabbitAnim_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_43A53F9C494FCBCB2CEFBE86C56DE89C_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_BlendListByBool_3ED3A5234C290E7670FA09ACB16AB009
struct UBP_SpaceRabbitAnim_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_BlendListByBool_3ED3A5234C290E7670FA09ACB16AB009_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_95C9B5D44BCDA4CEF670EBB734C4A8F4
struct UBP_SpaceRabbitAnim_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_95C9B5D44BCDA4CEF670EBB734C4A8F4_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_BC94D5694403857CB8DEDDA029F68D74
struct UBP_SpaceRabbitAnim_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_BC94D5694403857CB8DEDDA029F68D74_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_E8FFBF204DA6861069E9149F01F9FF43
struct UBP_SpaceRabbitAnim_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_E8FFBF204DA6861069E9149F01F9FF43_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_6E42E47E45FF613C112A249ED5554D59
struct UBP_SpaceRabbitAnim_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_6E42E47E45FF613C112A249ED5554D59_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_ModifyBone_6A5CA0404E2B1E50234BE081DC7C5118
struct UBP_SpaceRabbitAnim_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_ModifyBone_6A5CA0404E2B1E50234BE081DC7C5118_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_3F5FFFBF48CEAC7871D8BD962E09D99B
struct UBP_SpaceRabbitAnim_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_3F5FFFBF48CEAC7871D8BD962E09D99B_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_5BB219974AC2DFDD753F66B1CF15890B
struct UBP_SpaceRabbitAnim_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_5BB219974AC2DFDD753F66B1CF15890B_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_8B45377442C26E72DA2C7EB657B4E0DC
struct UBP_SpaceRabbitAnim_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_8B45377442C26E72DA2C7EB657B4E0DC_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_ModifyBone_21C046014858272F36ACD99CC2B91637
struct UBP_SpaceRabbitAnim_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_ModifyBone_21C046014858272F36ACD99CC2B91637_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_6F4251AD48D878FDD82A498E418BA270
struct UBP_SpaceRabbitAnim_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_6F4251AD48D878FDD82A498E418BA270_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_9CA7EB434AE691EEB602DE9A79024A23
struct UBP_SpaceRabbitAnim_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_9CA7EB434AE691EEB602DE9A79024A23_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_ModifyBone_212E75224E3813307B39D4AAD82834A7
struct UBP_SpaceRabbitAnim_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_ModifyBone_212E75224E3813307B39D4AAD82834A7_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_BlendListByBool_CDE46D0E406C2C7B115217B442C3B1EB
struct UBP_SpaceRabbitAnim_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_BlendListByBool_CDE46D0E406C2C7B115217B442C3B1EB_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_ModifyBone_EA1A3E0A48E7040B3465848AE914E2D6
struct UBP_SpaceRabbitAnim_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_ModifyBone_EA1A3E0A48E7040B3465848AE914E2D6_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_5E6A3E864E0E84F1FCCD7EBE86D3A980
struct UBP_SpaceRabbitAnim_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_5E6A3E864E0E84F1FCCD7EBE86D3A980_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_DCC677D946EF69862AE703A42591159D
struct UBP_SpaceRabbitAnim_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_DCC677D946EF69862AE703A42591159D_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_6C69A4C14ED82AD71302CBA6837321AF
struct UBP_SpaceRabbitAnim_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_6C69A4C14ED82AD71302CBA6837321AF_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_ModifyBone_85D1071B4BA16210D9A1218DC3F0149A
struct UBP_SpaceRabbitAnim_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_ModifyBone_85D1071B4BA16210D9A1218DC3F0149A_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_E6D642C14A20575B54FBE899C1714391
struct UBP_SpaceRabbitAnim_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_E6D642C14A20575B54FBE899C1714391_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_BlendListByBool_F05E496F497128835F8787BB063D3B8D
struct UBP_SpaceRabbitAnim_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_BlendListByBool_F05E496F497128835F8787BB063D3B8D_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_RotationOffsetBlendSpace_6749118F4EC959615B06C8A9911F4098
struct UBP_SpaceRabbitAnim_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_RotationOffsetBlendSpace_6749118F4EC959615B06C8A9911F4098_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_EC89C93641EBDE9C6096D298D7E0B5D5
struct UBP_SpaceRabbitAnim_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_EC89C93641EBDE9C6096D298D7E0B5D5_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_BlendListByBool_63450C124C25051220BF81BAF5A4DF24
struct UBP_SpaceRabbitAnim_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_BlendListByBool_63450C124C25051220BF81BAF5A4DF24_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_RotationOffsetBlendSpace_95143CBA4AA82224BDEA069875123FF4
struct UBP_SpaceRabbitAnim_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_RotationOffsetBlendSpace_95143CBA4AA82224BDEA069875123FF4_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_RotateRootBone_9B1061534F03F92CC11686A9AA65C1E0
struct UBP_SpaceRabbitAnim_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_RotateRootBone_9B1061534F03F92CC11686A9AA65C1E0_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_6DA227DC453491367B1B2B8E98CF9575
struct UBP_SpaceRabbitAnim_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_6DA227DC453491367B1B2B8E98CF9575_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_05345F29433C77E9EABDC0BE4B937A12
struct UBP_SpaceRabbitAnim_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_05345F29433C77E9EABDC0BE4B937A12_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_B38A16EF497AE10F2F3B1BA14159D8B6
struct UBP_SpaceRabbitAnim_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpaceRabbitAnim_AnimGraphNode_TransitionResult_B38A16EF497AE10F2F3B1BA14159D8B6_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.BlueprintUpdateAnimation
struct UBP_SpaceRabbitAnim_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.OnRadialDamageTaken
struct UBP_SpaceRabbitAnim_C_OnRadialDamageTaken_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.OnPointDamageTaken
struct UBP_SpaceRabbitAnim_C_OnPointDamageTaken_Params
{
	struct FVector*                                    shootDIrection;                                           // (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData)
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.AnimNotify_AudioNotify_SpaceBunny_RTPC_2
struct UBP_SpaceRabbitAnim_C_AnimNotify_AudioNotify_SpaceBunny_RTPC_2_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.AnimNotify_AudioNotify_SpaceBunny_RTPC_3
struct UBP_SpaceRabbitAnim_C_AnimNotify_AudioNotify_SpaceBunny_RTPC_3_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.AnimNotify_AudioNotify_SpaceBunny_RTPC_4
struct UBP_SpaceRabbitAnim_C_AnimNotify_AudioNotify_SpaceBunny_RTPC_4_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.AnimNotify_AudioNotify_SpaceBunny_SupressBreath
struct UBP_SpaceRabbitAnim_C_AnimNotify_AudioNotify_SpaceBunny_SupressBreath_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.AnimNotify_AudioNotify_SpaceBunny_ReleaseBreath
struct UBP_SpaceRabbitAnim_C_AnimNotify_AudioNotify_SpaceBunny_ReleaseBreath_Params
{
};

// Function BP_SpaceRabbitAnim.BP_SpaceRabbitAnim_C.ExecuteUbergraph_BP_SpaceRabbitAnim
struct UBP_SpaceRabbitAnim_C_ExecuteUbergraph_BP_SpaceRabbitAnim_Params
{
	int                                                EntryPoint;                                               // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
