// This file has been automatically generated by the Unreal Header Implementation tool

#include "UI/FGButtonHintBar.h"

void UFGButtonHintBar::NativeConstruct(){ Super::NativeConstruct(); }
void UFGButtonHintBar::UpdateButtonHints(const TArray<FFGButtonHintDescription>& buttonHints){ }
void UFGButtonHintBar::UpdateKeyHintsFromWidgetPath(){ }
void UFGButtonHintBar::HandleSlateFocusChanging(const FFocusEvent& FocusEvent, const FWeakWidgetPath& OldFocusedWidgetPath, const TSharedPtr<SWidget>& OldFocusedWidget, const FWidgetPath& NewFocusedWidgetPath, const TSharedPtr<SWidget>& NewFocusedWidget){ }
void UFGButtonHintBar::HandleKeyHintsChanged(){ }
void UFGButtonHintBar::UpdateKeyHintsFromFocusPath(const FWidgetPath& FocusPath){ }
void UFGButtonHintBar::HandleEnhancedInputMappingsRebuilt(){ }
void UFGButtonHintBar::UpdateKeyHintsFromEnhancedInput(){ }
UEnhancedInputLocalPlayerSubsystem* UFGButtonHintBar::GetEnhancedInputSubsystem() const{ return nullptr; }
void UFGButtonHintFunctionLibrary::GroupAndSortKeyHints(const TArray<FFGKeyHint>& KeyHints, TArray<FFGKeyHintGroup>& out_Groups){ }
