// This file has been automatically generated by the Unreal Header Implementation tool

#include "UI/FGListView.h"

TSharedRef<STableViewBase> UFGListView::RebuildListWidget() {
  return ConstructListView<SFGListView>();
}

UFGListView::UFGListView(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) {
	this->mWidgetBarStyle.Thickness = 8.0;
}
UUserWidget* UFGListView::GetEntryWidgetForItem(UObject* item) const{ return nullptr; }
