// This file has been automatically generated by the Unreal Header Implementation tool

#include "UI/FGOptionsValueController.h"

void UFGOptionsValueController::InitValueController(FOptionRowData optionRowData, UFGDynamicOptionsRow* parentOptionRow){ }
bool UFGOptionsValueController::IsPendingApply_Implementation(){ return bool(); }
bool UFGOptionsValueController::IsPendingRestart_Implementation(){ return bool(); }
bool UFGOptionsValueController::ShouldBeClickable_Implementation(){ return bool(); }
void UFGOptionsValueController::OnOptionReverted_Implementation(){ }
FText UFGOptionsValueController::GetCurrentSelectionText(){ return FText(); }
bool UFGOptionsValueController::ChangeSelection(FText currentKey, bool incrementSelection){ return bool(); }
void UFGOptionsValueController::NativeConstruct(){ }
bool UFGOptionsValueController::GetBoolOptionValue(){ return bool(); }
