// This file has been automatically generated by the Unreal Header Implementation tool

#include "UI/FGSequencerWidget.h"

void UFGSequencerWidget::NativeConstruct(){ }
void UFGSequencerWidget::NativeDestruct(){ }
void UFGSequencerWidget::ListenForInput(FInputChord inputkeyChord, TEnumAsByte<EInputEvent> eventType, bool consume, FOnInputAction callback){ }
void UFGSequencerWidget::StopListeningForAllInputs(){ }
void UFGSequencerWidget::MoveCursorForward(){ }
void UFGSequencerWidget::MoveCursorBackward(){ }
void UFGSequencerWidget::AddCurrentPlayerLocation(){ }
void UFGSequencerWidget::AddCurrentPlayerRotation(){ }
void UFGSequencerWidget::AddCurrentPlayerFOV(){ }
void UFGSequencerWidget::AddCurrentPlayerLocRotFOV(){ }
void UFGSequencerWidget::ToggleMouseControl(){ }
void UFGSequencerWidget::ListenForInputActionHelper(FInputChord inputkeyChord, bool consume, FOnInputAction pressedCallback, FOnInputAction releasedCallback, FOnInputAction doubleClickCallback, bool listenForRepeatedPressed){ }
