// This file has been automatically generated by the Unreal Header Implementation tool

#include "Atmosphere/BiomeHelpers.h"

void FBiomeHelpers::GetExponentialFogSettings(UFGBiome *biome, float atTime,  FExponentialFogSettings& out_settings){ }
void FBiomeHelpers::GetSkySphereSettings(UFGBiome *biome, float atTime,  FSkySphereSettings& out_settings){ }
void FBiomeHelpers::GetAtmosphereSettings(UFGBiome *biome, float atTime,  FSkyAtmosphereSettings& out_settings){ }
