// This file has been automatically generated by the Unreal Header Implementation tool

#include "Buildables/FGBuildablePortalSatellite.h"

AFGBuildablePortalSatellite::AFGBuildablePortalSatellite() : Super() {
	this->mWasHeatingUpLastTick = false;
}
bool AFGBuildablePortalSatellite::CanProduce_Implementation() const{ return bool(); }
void AFGBuildablePortalSatellite::Factory_TickProducing(float dt){ }
void AFGBuildablePortalSatellite::Factory_StopProducing(){ }
float AFGBuildablePortalSatellite::GetMainPortalHeatUpProgress() const{ return float(); }
EFGPortalLinkCandidateState AFGBuildablePortalSatellite::CanLinkToPortal(AFGBuildablePortalBase* otherPortal) const{ return EFGPortalLinkCandidateState(); }
float AFGBuildablePortalSatellite::GetProducingPowerConsumptionBase_ForPortal() const{ return float(); }
