// This file has been automatically generated by the Unreal Header Implementation tool

#include "Buildables/FGBuildableManufacturerVariablePower.h"

AFGBuildableManufacturerVariablePower::AFGBuildableManufacturerVariablePower() : Super() {
	this->mEstimatedMininumPowerConsumption = 0.0;
	this->mEstimatedMaximumPowerConsumption = 0.0;
	this->mPowerConsumptionCurve = nullptr;
}
void AFGBuildableManufacturerVariablePower::BeginPlay(){ Super::BeginPlay(); }
float AFGBuildableManufacturerVariablePower::GetProducingPowerConsumptionBase() const{ return Super::GetProducingPowerConsumptionBase(); }
void AFGBuildableManufacturerVariablePower::Factory_StartProducing(){ }
void AFGBuildableManufacturerVariablePower::Factory_TickProducing(float dt){ }
float AFGBuildableManufacturerVariablePower::GetMinPowerConsumption() const{ return float(); }
float AFGBuildableManufacturerVariablePower::GetMaxPowerConsumption() const{ return float(); }
void AFGBuildableManufacturerVariablePower::Factory_Tick(float dt){ }
void AFGBuildableManufacturerVariablePower::OnRep_CurrentPotential(){ }
void AFGBuildableManufacturerVariablePower::OnRep_CurrentProductionBoost(){ }
void AFGBuildableManufacturerVariablePower::OnRep_IsProducing(){ }
void AFGBuildableManufacturerVariablePower::OnRep_CurrentRecipe(){ }
void AFGBuildableManufacturerVariablePower::UpdateVariablePowerConsumption(){ }
void AFGBuildableManufacturerVariablePower::UpdatePowerConsumptionLimits(){ }
float AFGBuildableManufacturerVariablePower::ApplyRecipePowerModifications(float curveValue){ return float(); }
