// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGBuildablePowerPole.h"
#include "FGColoredInstanceMeshProxy.h"
AFGBuildablePowerPole::AFGBuildablePowerPole(){
	// MODDING EDIT: Objects appear to have this without it being added for us -> Adding it here.
	mMeshComponentProxy = CreateOptionalDefaultSubobject<UFGColoredInstanceMeshProxy>(FName("PoleMeshProxy")); mMeshComponentProxy->SetupAttachment(RootComponent);
}
void AFGBuildablePowerPole::BeginPlay(){ }
void AFGBuildablePowerPole::GetLifetimeReplicatedProps(TArray< FLifetimeProperty >& OutLifetimeProps) const{ }
void AFGBuildablePowerPole::StartIsLookedAtForConnection( AFGCharacterPlayer* byCharacter){ }
void AFGBuildablePowerPole::StopIsLookedAtForConnection( AFGCharacterPlayer* byCharacter){ }
void AFGBuildablePowerPole::ShowConnectionFeedback(){ }
void AFGBuildablePowerPole::HideConnectionFeedback(){ }
void AFGBuildablePowerPole::Dismantle_Implementation(){ }
void AFGBuildablePowerPole::OnBuildEffectFinished(){ }
UFGPowerCircuit* AFGBuildablePowerPole::GetPowerCircuit() const{ return nullptr; }
void AFGBuildablePowerPole::OnPowerConnectionChanged( UFGCircuitConnectionComponent* connection){ }
void AFGBuildablePowerPole::MarkConnectionsDirty(){ }
