// This file has been automatically generated by the Unreal Header Implementation tool

#include "Buildables/FGBuildablePoleBase.h"

bool AFGBuildablePoleBase::ShouldBeConsideredForBase_Implementation(){ return bool(); }
bool AFGBuildablePoleBase::ShouldShowCenterGuidelinesForHologram(const AFGHologram* hologram) const{ return bool(); }
