// This file has been automatically generated by the Unreal Header Implementation tool

#include "Buildables/FGBuildablePoleBase.h"

#if WITH_EDITORONLY_DATA
#endif 
#if WITH_EDITOR
void AFGBuildablePoleBase::PostEditChangeProperty(FPropertyChangedEvent& PropertyChangedEvent){ Super::PostEditChangeProperty(PropertyChangedEvent); }
#endif 
bool AFGBuildablePoleBase::ShouldBeConsideredForBase_Implementation(){ return bool(); }
void AFGBuildablePoleBase::PostLoad(){ Super::PostLoad(); }
void AFGBuildablePoleBase::EndPlay(const EEndPlayReason::Type EndPlayReason){ }
