// This file has been automatically generated by the Unreal Header Implementation tool

#include "Equipment/FGEquipmentStunSpear.h"
#include "Components/SceneComponent.h"
#include "DamageTypes/FGDamageType.h"

AFGEquipmentStunSpear::AFGEquipmentStunSpear() : Super() {
	this->mCollisionComp = nullptr;
	this->mDamageTypeClass = UFGDamageType::StaticClass();
	this->mSecondSwingMaxTime = 0.7;
	this->mSecondSwingCooldDownTime = 1.0;
	this->mDamage = 10;
	this->mAttackDistance = 100.0;
	this->mArmAnimation = EArmEquipment::AE_StunSpear;
	this->RootComponent = CreateDefaultSubobject<USceneComponent>(TEXT("RootComponent"));
}
void AFGEquipmentStunSpear::AddEquipmentActionBindings(){ }
void AFGEquipmentStunSpear::DoAttack(){ }
void AFGEquipmentStunSpear::OnHitTarget_Implementation(){ }
void AFGEquipmentStunSpear::Server_ShockEnemy_Implementation(){ }
bool AFGEquipmentStunSpear::Server_ShockEnemy_Validate(){ return bool(); }
void AFGEquipmentStunSpear::OnFirePressed(){ }
