// This file has been automatically generated by the Unreal Header Implementation tool

#include "FGBuildingDescriptor.h"

#if WITH_EDITOR
void UFGBuildingDescriptor::SetupStage(){ }
FVector UFGBuildingDescriptor::GetCenterOfCollision(){ return FVector(); }
void UFGBuildingDescriptor::SetBuildableClass(TSubclassOf< UFGBuildingDescriptor > inClass, TSubclassOf<  AFGBuildable > buildableClass){ }
#endif 
UFGBuildingDescriptor::UFGBuildingDescriptor() : Super() {
	this->mDisplayName = INVTEXT("");
	this->mDescription = INVTEXT("");
	this->mStackSize = EStackSize::SS_MEDIUM;
	this->mCanBeDiscarded = true;
	this->mPreviewView.Distance = 1200; this->mPreviewView.FocalOffset.X = 0; this->mPreviewView.FocalOffset.Y = 0; this->mPreviewView.FocalOffset.Z = 0; this->mPreviewView.CameraPitch = -35;
}
void UFGBuildingDescriptor::PostLoad(){ Super::PostLoad(); }
TSubclassOf< class AFGBuildable > UFGBuildingDescriptor::GetBuildableClass(TSubclassOf< UFGBuildingDescriptor > inClass){ return TSubclassOf<class AFGBuildable>(); }
float UFGBuildingDescriptor::GetPowerConsumption(TSubclassOf< UFGBuildingDescriptor > inClass){ return float(); }
float UFGBuildingDescriptor::GetPowerProduction(TSubclassOf< UFGBuildingDescriptor > inClass){ return float(); }
FText UFGBuildingDescriptor::GetItemNameInternal() const{ return FText(); }
FText UFGBuildingDescriptor::GetItemDescriptionInternal() const{ return FText(); }
TSubclassOf< class AFGHologram > UFGBuildingDescriptor::GetHologramClassInternal() const{ return TSubclassOf<class AFGHologram>(); }
TSubclassOf< AActor > UFGBuildingDescriptor::GetBuildClassInternal() const{ return TSubclassOf<AActor>(); }
FText UFGBuildingDescriptor::mOverrideDisplayNameAndDescription = FText();
