// This file has been automatically generated by the Unreal Header Implementation tool

#include "Resources/FGDecorDescriptor.h"

UFGDecorDescriptor::UFGDecorDescriptor(){ }
UStaticMesh* UFGDecorDescriptor::GetDecorMesh(TSubclassOf< UFGDecorDescriptor > inClass){ return nullptr; }
