// This file has been automatically generated by the Unreal Header Implementation tool

#include "Resources/FGExtractableResourceInterface.h"

UFGExtractableResourceInterface::UFGExtractableResourceInterface(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) {}
