// This file has been automatically generated by the Unreal Header Implementation tool

#include "Creature/Enemy/FGFlyingBabyCrab.h"

AFGFlyingBabyCrab::AFGFlyingBabyCrab() : Super() {

}
void AFGFlyingBabyCrab::BeginPlay(){ }
void AFGFlyingBabyCrab::EndPlay(const EEndPlayReason::Type EndPlayReason){ }
void AFGFlyingBabyCrab::PostNetReceiveLocationAndRotation(){ }
