// This file has been automatically generated by the Unreal Header Implementation tool

#include "Unlocks/FGUnlockScannableResource.h"

#if WITH_EDITORONLY_DATA
#endif 
void UFGUnlockScannableResource::Apply( AFGUnlockSubsystem* unlockSubssytem){ }
