// This file has been automatically generated by the Unreal Header Implementation tool

#include "FactoryDCModule.h"

#include "Networking/FGClientAPIManager.h"

void FFactoryDedicatedClientModule::StartupModule(){ }
void FFactoryDedicatedClientModule::ShutdownModule(){ }

IMPLEMENT_GAME_MODULE(FFactoryDedicatedClientModule, FactoryDedicatedClient);

void InternalProcessServerAPIRequest(UObject* Context, UFunction* Function, void* Params) {}
